---
apiVersion: v1
kind: Service
metadata:
  name: myapp-nap-sv
  namespace: myapp
spec:
  selector:
    app: myapp-nap
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-nap-deploy
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: myapp-nap
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: myapp-nap
    spec:
      containers:
        - image: 127.0.0.1:5001/myapp-front:v1.2
          #imagePullPolicy: Never
          name: myapp-nap-pod
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred

