---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: myapp
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxMjcuMC4wLjE6NTAwMSI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZZV1J0YVc0PSIKCQl9Cgl9Cn0= 
type: kubernetes.io/dockerconfigjson
