---
apiVersion: v1
kind: Service
metadata:
  name: myapp-front-sv
  namespace: myapp
spec:
  selector:
    app: myapp-front
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32016

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-front-deploy
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: myapp-front 
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: myapp-front
    spec:
      containers:
        - image: 127.0.0.1:5001/myapp-front:v4
          #imagePullPolicy: Never
          name: myapp-front-pod
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred

